### PR TITLE
mainnet_v1: upgrade to v1.3.0

### PR DESCRIPTION
**Pull request by Flouse**
## Release notes
- Godwoken 1.3.0-rc1
   https://github.com/nervosnetwork/godwoken/releases/tag/v1.3.0-rc1
- Polyjuice 1.3.0
   https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/1.3.0

## Image
- ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc2

## Related PR
- https://github.com/nervosnetwork/godwoken-info/pull/45

### CODE REVIEW

**Comment by Gridzilla** [comment]
@Flouse 
Trying to run the docker-compose file on a VirtualBox Linux VM, and also on a VSphere VM both yield a failure with Docker error 132 (SIGILL - illegal instruction). It happens on 1.3.0-rc2 as in this PR and also on 1.3.0-rc3, when I hand-modify the file. As far as I can see this is a showstopper for running a virtualized GW node. Are there specific CPU capabilities that are required to run GWv1?


-------------- Attempt on 1.2.0-rc1---------------------


sudo docker run -it ghcr.io/nervosnetwork/godwoken-prebuilds:1.2.0-rc1 /bin/bash
Unable to find image 'ghcr.io/nervosnetwork/godwoken-prebuilds:1.2.0-rc1' locally
1.2.0-rc1: Pulling from nervosnetwork/godwoken-prebuilds
(...)
Status: Downloaded newer image for ghcr.io/nervosnetwork/godwoken-prebuilds:1.2.0-rc1
root@27285e738f08:/# godwoken
Error: read config file from ./config.toml

Caused by:
    No such file or directory (os error 2)
root@27285e738f08:/# 

-------------- Attempt on 1.3.0-rc1---------------------

sudo docker run -it ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc1 /bin/bash
Unable to find image 'ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc1' locally
1.3.0-rc1: Pulling from nervosnetwork/godwoken-prebuilds
(...)
Status: Downloaded newer image for ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc1
root@1afd77b632cd:/# godwoken    
Illegal instruction (core dumped)


[strace.txt](https://github.com/nervosnetwork/godwoken-info/files/9105693/strace.txt)

**Comment by Flouse** [comment]
> Are there specific CPU capabilities that are required to run GWv1?

We have compiled and built a more compatible image:
- https://github.com/nervosnetwork/godwoken-docker-prebuilds/pull/66
  Explicitly target AVX2 instead of using -march=native for RocksDB which may produce binaries that require AVX-512.
  

Please try ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc3
@Gridzilla

**Comment by Gridzilla** [comment]
> Please try ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc3

Same result. Exits with SIGILL

I succesfully deployed a local node using your PR modified to use the 1.2-rc Godwoken prebuild so my environment is OK.
On the other hand all 1.3.x prebuilds that I tried so far gave me the same error 132 - SIGILL
@Flouse 


Edit: I checked and the last prebuild that does not throw this error is `main-202206230545`. `1.3.0-rc1-202207010955` exits with error 132.

**Comment by Gridzilla** [comment]
I should add that for a 1.2-rc deployment it was not painless. Starting with an empty `chain-data` folder and `docker-compose up` causes the `gw-mainnet_v1-readonly` to stop syncing after about 2k blocks. After restarting it freezes up again after another 2k blocks. The workaround was to start with `docker-compose up -d gw-mainnet_v1-readonly`, wait for it to sync up, and only afterwards deploy the whole node with `docker-compose up`

**Comment by Flouse** [comment]
> I should add that for a 1.2-rc deployment it was not painless. Starting with an empty `chain-data` folder and `docker-compose up` causes the `gw-mainnet_v1-readonly` to stop syncing after about 2k blocks. After restarting it freezes up again after another 2k blocks. The workaround was to start with `docker-compose up -d gw-mainnet_v1-readonly`, wait for it to sync up, and only afterwards deploy the whole node with `docker-compose up`

Got it.
I will add [healthcheck](https://github.com/nervosnetwork/godwoken-info/blob/main/testnet_v1_1/healthcheck.sh) into docker-compose.yml later.

**Comment by blckngm** [comment]
> > Please try ghcr.io/nervosnetwork/godwoken-prebuilds:1.3.0-rc3
> 
> Same result. Exits with SIGILL

Most likely it's because your VM does not support AVX2. What's the output if you run `grep avx2 /proc/cpuinfo`?

We will try to make running godwoken smoother for CPUs/environments that does not support AVX/AVX2 in the future.

Meanwhile, if your CPU supports AVX2, you can try to tweak some settings to make the VM support it too.

Or you can build godwoken in the VM to produce a binary that does not use AVX/AVX2.

**Comment by Gridzilla** [comment]
> Most likely it's because your VM does not support AVX2. What's the output if you run `grep avx2 /proc/cpuinfo`?

That was it. Thanks for clarifying!

> We will try to make running godwoken smoother for CPUs/environments that does not support AVX/AVX2 in the future.

This would be very welcome and make it easier to launch nodes, but as long as it is clear that this is a requirement people can plan their way around it.

**Comment by Gridzilla** [comment]
Oh wow the 1.3 version with AVX is significantly faster. I like that a lot!

**Comment by Flouse** [comment]
[GwScan mainnet_v1](https://v1.gwscan.com/) has been upgraded to v1.3.0
cc @jjyr

**Review by jjyr — APPROVED** [review]

**Pull request merged**
